id: sample
seed: 3698
model:
    name: XGBoost
    args:
        n_estimators: 200
        max_depth: 7
        max_features: 'auto'
        min_samples_split: 7
        min_samples_leaf: 3
        learning_rate: 0.3

dataset:
    train:
        name: data-train
        args:
            path: 'data/processed/data-train/input'
            ratio: 0.4
        
    inference:
        name: public-test
        args:
            path: 'data/processed/public-test/input'
            Kneighbor: 4
    
trainer:
    log_dir: saved/log
    model_dir: saved/models