id: sample
seed: 3698
model:
    name: XGBoost
    args:
        n_estimators: 1000
        max_depth: 7
        max_features: 'auto'
        min_samples_split: 7
        min_samples_leaf: 3
        learning_rate: 0.3

dataset:
    train:
        name: data-train
        args:
            paths: ['data/raw/data-train/input', 'data/raw/data-train/output']
            ratio: 0.4
    
trainer:
    log_dir: saved/logs_fill_nan_models
    model_dir: saved/fill_nan_models