id: sample
seed: 3698

model:
  # name: XGBoost
  # args:
  #   n_estimators: 200
  #   max_depth: 7 #7
  #   max_features: "auto"
  #   min_samples_split: 7
  #   min_samples_leaf: 3
  #   learning_rate: 0.17 #0.17
  #   gamma: 1
  #   reg_alpha: 0
  #   reg_lambda: 1

  # name: CatBoost
  # args:
  #   iterations: 500
  #   learning_rate: 0.01
  #   depth: 10
  #   eval_metric: "RMSE"
  #   bagging_temperature: 0.2
  #   od_type: "Iter"
  #   metric_period: 50
  #   od_wait: 20
  #   # task_type: "GPU"
  #   # devices: '0:1'

  name: LSTM
  args:

dataset:
  train:
    name: data-train
    args:
      path: "data/processed/data-train/input"
      # path: "data/processed_interpolate/data-train/input"
      # path: 'data/processed_new_fill_nan/data-train/input'
      ratio: 0.22

  inference:
    name: public-test
    args:
      path: "data/processed/public-test/input"
      # path: "data/processed_interpolate/public-test/input"
      Kneighbor: 4

trainer:
  log_dir: saved/log
  model_dir: saved/models
